---
description: Исключения могут инициироваться оборудованием или программным обеспечением и могут происходить в режиме ядра, а также в коде пользовательского режима. Структурированная обработка исключений предоставляет единый механизм для обработки исключений режима ядра и пользовательского режима.
ms.assetid: 760ddcaa-a18c-4fdf-836c-9028a2e4b62e
title: Обработка исключений (обработка ошибок)
ms.topic: article
ms.date: 05/31/2018
ms.openlocfilehash: 4eb44cd294d89be81862c5330dda5b14811add1f
ms.sourcegitcommit: c7add10d695482e1ceb72d62b8a4ebd84ea050f7
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 01/07/2021
ms.locfileid: "104140790"
---
# <a name="exception-handling-error-handling"></a>Обработка исключений (обработка ошибок)

Исключения могут инициироваться оборудованием или программным обеспечением и могут происходить в режиме ядра, а также в коде пользовательского режима. Структурированная обработка исключений предоставляет единый механизм для обработки исключений режима ядра и пользовательского режима.

Выполнение определенных последовательностей инструкций может привести к исключениям, инициированным оборудованием. Например, нарушение прав доступа создается оборудованием, когда процесс пытается выполнить чтение или запись на виртуальный адрес, к которому он не имеет соответствующего доступа.

События, требующие обработки исключений, также могут возникать во время выполнения программной процедуры (например, если указано недопустимое значение параметра). В этом случае поток может инициировать исключение явным образом путем вызова функции [**RaiseException**](/windows/win32/api/errhandlingapi/nf-errhandlingapi-raiseexception) . Эта функция позволяет вызывающему потоку указывать сведения, описывающие исключение.

Исключение может быть непрерывным или недопустимым. Исключение, которое является непродолжаемым, возникает, когда событие не поддерживается в течение оборудования или если продолжение не имеет смысла. Исключение, которое не является непрерывным, не приводит к завершению работы приложения. Таким образом, приложение может перехватить исключение и выполнить команду. Однако непродолжаемое исключение обычно возникает в результате повреждения стека или другой серьезной проблемы, что затрудняет восстановление после исключения.

 

 
